services:
  fastapi:
    container_name: fastapi-app
    build: 
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c '../scripts/fastapi_application.sh'
    ports:
      - '8000:8000'
