[tool.poetry]
name = "user-service"
version = "0.1.0"
description = ""
authors = ["NxtaSunstrike <unixalle765@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.4"
sqlalchemy = "^2.0.35"
asyncpg = "^0.29.0"
gunicorn = "^23.0.0"
pyjwt = "^2.9.0"
nats-py = "^2.9.0"
dishka = "^1.3.0"
faststream = {extras = ["nats"], version = "^0.5.25"}
elasticsearch = "^8.15.1"
fastapi = "^0.115.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

