[tool.poetry]
name = "user-service"
version = "0.1.0"
description = ""
authors = ["NxtaSunstrike <unixalle765@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
asyncpg = "^0.30.0"
uvicorn = "^0.32.0"
motor = "^3.6.0"
sqlalchemy = "^2.0.36"
gunicorn = "^23.0.0"
alembic = "^1.14.0"
dishka = "^1.4.1"
fastapi = "^0.115.5"
faststream = {extras = ["cli"], version = "^0.5.30"}
aiokafka = "^0.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
