[tool.poetry]
name = "user-service"
version = "0.1.0"
description = ""
authors = ["NxtaSunstrike <unixalle765@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.6"
uvicorn = "^0.31.1"
sqlalchemy = "^2.0.35"
asyncpg = "^0.29.0"
fastapi = "^0.115.2"
faststream = {extras = ["nats"], version = "^0.5.25"}
dishka = "^1.3.0"
alembic = "^1.13.3"
python-dotenv = "^1.0.1"
pyjwt = "^2.9.0"
redis = "^5.1.1"
asynch = "^0.2.5"
motor = "^3.6.0"
prometheus-client = "^0.21.0"
opentelemetry-api = "^1.27.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
