target-version = 'py312'
line-length = 130

[lint]
select = ['ALL']
exclude = [
    ".git",
    "__pycache__"
]
ignore = [
    "D100", # Missing docstring in public module
    "D101", # Missing docstring in public class
    "D102", # Missing docstring in public method
    "D103", # Missing docstring in public function
    "D104", # Missing docstring in public package
    "D105", # Missing docstring in magic method
    "D107", # Missing docstring in `__init__`
]

[lint.pydocstyle]
convention = "pep257"