from app.domain.exception import DomainException


class InvalidContactsError(DomainException):
    ...

class InvalidFullNameError(DomainException):
    ...

class UserInactiveError(DomainException):
    ...

class ProfileInactiveError(DomainException):
    ...

class SocialNetwProfileNotFoundError(DomainException):
    ...

class AddressNotFoundError(DomainException):
    ...

class AvatarNotFoundError(DomainException):
    ...
