from app.domain.common.common_domain_exception import CommonDomainException


class InvalidAddressException(CommonDomainException):
    ...

class InvalidBioException(CommonDomainException):
    ...

class InvalidDateOfBirthException(CommonDomainException):
    ...

class InvalidFirstNameException(CommonDomainException):
    ...

class InvalidLastNameException(CommonDomainException):
    ...

class InvalidGenderException(CommonDomainException):
    ...

class InvalidInterestsException(CommonDomainException):
    ...

class InvalidLastNameException(CommonDomainException):
    ...

class InvalidMiddleNameException(CommonDomainException):
    ...

class InvalidProfilePictureException(CommonDomainException):
    ...

class InvalidProfileTypeException(CommonDomainException):
    ...

class InvalidSocialProfileException(CommonDomainException):
    ...
