"""empty message

Revision ID: a0805a2ee1fd
Revises: ee2a01e84df4
Create Date: 2024-11-27 04:33:26.078830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0805a2ee1fd'
down_revision: Union[str, None] = 'ee2a01e84df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.execute('ALTER TABLE users ALTER COLUMN phone_number TYPE INTEGER USING phone_number::integer')
    op.drop_column('users', 'delete_date')
    op.drop_column('users', 'created_date')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE users ALTER COLUMN phone_number TYPE VARCHAR')
    op.add_column('users', sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('delete_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###
