"""empty message

Revision ID: ee2a01e84df4
Revises: 
Create Date: 2024-11-27 03:14:00.666401

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee2a01e84df4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("users",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("username", sa.String(), nullable=False),
    sa.Column("email", sa.String(), nullable=True),
    sa.Column("phone_number", sa.String(), nullable=True),
    sa.Column("delete_date", sa.DateTime(), nullable=True),
    sa.Column("created_date", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("email"),
    sa.UniqueConstraint("phone_number"),
    sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
