"""empty message

Revision ID: 0904154c9756
Revises: 
Create Date: 2024-12-18 14:27:52.717429

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0904154c9756"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("users",
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("email", sa.String(length=255), nullable=True),
    sa.Column("phone_number", sa.Integer(), nullable=True),
    sa.Column("username", sa.String(length=255), nullable=False),
    sa.Column("status", sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint("user_id"),
    sa.UniqueConstraint("email"),
    sa.UniqueConstraint("phone_number"),
    sa.UniqueConstraint("username"),
    )
    op.create_table("profiles",
    sa.Column("profile_id", sa.UUID(), nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=True),
    sa.Column("first_name", sa.String(length=255), nullable=False),
    sa.Column("last_name", sa.String(length=255), nullable=True),
    sa.Column("middle_name", sa.String(length=255), nullable=True),
    sa.Column("bio", sa.String(length=255), nullable=False),
    sa.Column("status", sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.user_id"] ),
    sa.PrimaryKeyConstraint("profile_id"),
    )
    op.create_table("addresses",
    sa.Column("address_id", sa.UUID(), nullable=False),
    sa.Column("profile_id", sa.UUID(), nullable=True),
    sa.Column("country", sa.String(length=255), nullable=False),
    sa.Column("city", sa.String(length=255), nullable=False),
    sa.Column("street", sa.String(length=255), nullable=False),
    sa.Column("house_number", sa.String(length=255), nullable=False),
    sa.Column("apartament_number", sa.String(length=255), nullable=True),
    sa.Column("postal_code", sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(["profile_id"], ["profiles.profile_id"] ),
    sa.PrimaryKeyConstraint("address_id"),
    )
    op.create_table("social_netw_profiles",
    sa.Column("social_netw_profile_id", sa.UUID(), nullable=False),
    sa.Column("profile_id", sa.UUID(), nullable=True),
    sa.Column("social_netw_profile_name", sa.String(length=255), nullable=False),
    sa.Column("social_netw_profile_link", sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(["profile_id"], ["profiles.profile_id"] ),
    sa.PrimaryKeyConstraint("social_netw_profile_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("social_netw_profiles")
    op.drop_table("addresses")
    op.drop_table("profiles")
    op.drop_table("users")
    # ### end Alembic commands ###
