"""empty message

Revision ID: f0a73d06bcb1
Revises: f8116d47466e
Create Date: 2024-12-19 11:55:08.489482

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0a73d06bcb1"
down_revision: str | None = "f8116d47466e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("addresses_profile_id_fkey", "addresses", type_="foreignkey")
    op.create_foreign_key(None, "addresses", "profiles", ["profile_id"], ["profile_id"], ondelete="CASCADE")
    op.drop_constraint("social_netw_profiles_profile_id_fkey", "social_netw_profiles", type_="foreignkey")
    op.create_foreign_key(None, "social_netw_profiles", "profiles", ["profile_id"], ["profile_id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "social_netw_profiles", type_="foreignkey")
    op.create_foreign_key("social_netw_profiles_profile_id_fkey", "social_netw_profiles", "profiles", ["profile_id"], ["profile_id"])
    op.drop_constraint(None, "addresses", type_="foreignkey")
    op.create_foreign_key("addresses_profile_id_fkey", "addresses", "profiles", ["profile_id"], ["profile_id"])
    # ### end Alembic commands ###
