"""empty message

Revision ID: f8116d47466e
Revises: 4f75d09dfb10
Create Date: 2024-12-19 09:27:35.429834

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f8116d47466e"
down_revision: str | None = "4f75d09dfb10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
