from app.domain.base.base_exception import BaseDomainError


class TimestampTypeError(BaseDomainError):
    ...

class TimestampRequiredError(BaseDomainError):
    ...

class UserEmailTypeError(BaseDomainError):
    ...

class MinimalLenghtEmailError(BaseDomainError):
    ...

class MaximalLenghtEmailError(BaseDomainError):
    ...

class FirstNameRequiredError(BaseDomainError):
    ...

class FirstNameTypeError(BaseDomainError):
    ...

class MinimalLenghtFirstNameError(BaseDomainError):
    ...

class MaximalLenghtFirstNameError(BaseDomainError):
    ...

class LastNameRequiredError(BaseDomainError):
    ...

class LastNameTypeError(BaseDomainError):
    ...

class MinimalLenghtLastNameError(BaseDomainError):
    ...

class MaximalLenghtLastNameError(BaseDomainError):
    ...

class MiddleNameTypeError(BaseDomainError):
    ...

class MinimalLenghtMiddleNameError(BaseDomainError):
    ...

class MaximalLenghtMiddleNameError(BaseDomainError):
    ...

class UserPhoneTypeError(BaseDomainError):
    ...

class MinimalLenghtUserPhoneError(BaseDomainError):
    ...

class MaximalLenghtUserPhoneError(BaseDomainError):
    ...

class UUIDTypeError(BaseDomainError):
    ...

class UUIDRequiredError(BaseDomainError):
    ...

class ContactsRequiredError(BaseDomainError):
    ...
