from app.domain.common.common_exceptions import CommonDomainError


class TimestampTypeError(CommonDomainError):
    ...

class TimestampRequiredError(CommonDomainError):
    ...

class UserEmailTypeError(CommonDomainError):
    ...

class MinimalLenghtEmailError(CommonDomainError):
    ...

class MaximalLenghtEmailError(CommonDomainError):
    ...

class FirstNameRequiredError(CommonDomainError):
    ...

class FirstNameTypeError(CommonDomainError):
    ...

class MinimalLenghtFirstNameError(CommonDomainError):
    ...

class MaximalLenghtFirstNameError(CommonDomainError):
    ...

class LastNameRequiredError(CommonDomainError):
    ...

class LastNameTypeError(CommonDomainError):
    ...

class MinimalLenghtLastNameError(CommonDomainError):
    ...

class MaximalLenghtLastNameError(CommonDomainError):
    ...

class MiddleNameTypeError(CommonDomainError):
    ...

class MinimalLenghtMiddleNameError(CommonDomainError):
    ...

class MaximalLenghtMiddleNameError(CommonDomainError):
    ...

class UserPhoneTypeError(CommonDomainError):
    ...

class MinimalLenghtUserPhoneError(CommonDomainError):
    ...

class MaximalLenghtUserPhoneError(CommonDomainError):
    ...

class UUIDTypeError(CommonDomainError):
    ...

class UUIDRequiredError(CommonDomainError):
    ...

class ContactsRequiredError(CommonDomainError):
    ...